import 'dart:typed_data';

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart' show kDebugMode;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../calc_engine.dart';
import '../models/business_profile.dart';
import '../models/trade_purchase_models.dart';
import 'purchase_invoice_amount_words.dart';
import 'purchase_invoice_pdf_layout.dart';

final _money = NumberFormat('#,##,##0.00', 'en_IN');
String _inrPdf(num n) => 'Rs. ${_money.format(n)}';
final _dateFmt = DateFormat('dd MMM yyyy');

const _muted = PdfColor.fromInt(0xFF475569);
const _border = PdfColor.fromInt(0xFFD1D5DB);

Future<pw.ImageProvider?> _tryLogo(String? url) async {
  final u = url?.trim();
  if (u == null || u.isEmpty) return null;
  try {
    final r = await Dio().get<List<int>>(
      u,
      options: Options(
        responseType: ResponseType.bytes,
        receiveTimeout: const Duration(seconds: 8),
      ),
    );
    final data = r.data;
    if (data == null || data.isEmpty) return null;
    return pw.MemoryImage(Uint8List.fromList(data));
  } catch (_) {
    return null;
  }
}

String _partyName(String? s) => (s == null || s.trim().isEmpty) ? '—' : s.trim();

/// One-page receipt: ASCII money, minimal lines.
Future<pw.Document> buildPurchaseReceiptDoc(
  TradePurchase p,
  BusinessProfile biz,
) async {
  final brokerAmt = purchaseBrokerCommissionForReceipt(p);
  final doc = pw.Document();
  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      build: (ctx) => [
        pw.Text(
          biz.displayTitle.trim().isNotEmpty ? biz.displayTitle : 'Business',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        if (biz.address != null && biz.address!.trim().isNotEmpty)
          pw.Text(
            biz.address!.trim(),
            style: const pw.TextStyle(fontSize: 9, color: _muted, height: 1.35),
          ),
        if (biz.phone != null && biz.phone!.trim().isNotEmpty)
          pw.Text(
            'Phone: ${biz.phone!.trim()}',
            style: const pw.TextStyle(fontSize: 9, color: _muted),
          ),
        pw.SizedBox(height: 14),
        pw.Text(
          'Purchase ${p.humanId}',
          style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          'Supplier: ${_partyName(p.supplierName)}',
          style: const pw.TextStyle(fontSize: 10.5),
        ),
        if (p.brokerName != null && p.brokerName!.trim().isNotEmpty)
          pw.Text(
            'Broker: ${_partyName(p.brokerName)}',
            style: const pw.TextStyle(fontSize: 10.5),
          ),
        pw.Text(
          'Date: ${_dateFmt.format(p.purchaseDate)}',
          style: const pw.TextStyle(fontSize: 10.5),
        ),
        pw.SizedBox(height: 12),
        pw.Text(
          'Items',
          style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        for (final l in p.lines) ...[
          pw.Text(
            l.itemName,
            style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
          ),
          pw.Text(
            '  ${l.qty} ${l.unit}  ·  line total ${_inrPdf(lineMoney(tradePurchaseLineToCalcLine(l)))}',
            style: const pw.TextStyle(fontSize: 9.5, color: _muted),
          ),
          pw.SizedBox(height: 6),
        ],
        pw.Container(height: 1, color: _border),
        pw.SizedBox(height: 8),
        pw.Text(
          'Total: ${_inrPdf(p.totalAmount)}',
          style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
        ),
        pw.Text(
          'Full invoice: line tax, HSN, and terms on the main PDF export.',
          style: const pw.TextStyle(fontSize: 7.5, color: _muted, height: 1.25),
        ),
        if (brokerAmt > 0)
          pw.Text(
            'Broker commission: ${_inrPdf(brokerAmt)}',
            style: const pw.TextStyle(fontSize: 10),
          ),
        pw.SizedBox(height: 6),
        pw.Text(
          'Paid ${_inrPdf(p.paidAmount)}  ·  Balance ${_inrPdf(p.remaining)}',
          style: const pw.TextStyle(fontSize: 9, color: _muted),
        ),
        pw.SizedBox(height: 10),
        pw.Text(
          'Amount in words: ${amountInWordsInr(p.totalAmount)}',
          style: const pw.TextStyle(fontSize: 8, color: _muted, height: 1.2),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          'Generated by Harisree Exp&Pur',
          style: const pw.TextStyle(fontSize: 7.5, color: _muted),
        ),
      ],
    ),
  );
  return doc;
}

/// Professional A4 purchase invoice; totals match [computeTradeTotals] / server [totalAmount].
Future<pw.Document> buildPurchaseDoc(TradePurchase p, BusinessProfile biz) async {
  final logo = await _tryLogo(biz.logoUrl);
  final doc = await buildProfessionalPurchaseInvoiceDoc(
    purchase: p,
    business: biz,
    logo: logo,
  );
  final req = tradeCalcRequestFromTradePurchase(p);
  final t = computeTradeTotals(req);
  if ((t.amountSum - p.totalAmount).abs() >= 0.02 && kDebugMode) {
    assert(false, 'PDF total ${t.amountSum} != purchase.totalAmount ${p.totalAmount}');
  }
  return doc;
}

Future<void> sharePurchasePdf(TradePurchase p, BusinessProfile biz) async {
  final doc = await buildPurchaseDoc(p, biz);
  await Printing.sharePdf(bytes: await doc.save(), filename: '${p.humanId}.pdf');
}

Future<void> printPurchasePdf(TradePurchase p, BusinessProfile biz) async {
  final doc = await buildPurchaseDoc(p, biz);
  await Printing.layoutPdf(onLayout: (_) async => doc.save());
}

Future<void> downloadPurchasePdf(TradePurchase p, BusinessProfile biz) async {
  final doc = await buildPurchaseDoc(p, biz);
  await Printing.layoutPdf(onLayout: (_) async => doc.save());
}

Future<void> sharePurchaseFullInvoicePdf(
  TradePurchase p,
  BusinessProfile biz,
) async {
  final doc = await buildPurchaseDoc(p, biz);
  await Printing.sharePdf(bytes: await doc.save(), filename: '${p.humanId}_full.pdf');
}
