from __future__ import annotations

import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
TEMPLATE_PATH = DOCS_DIR / "_STRICT_MD_TEMPLATE.md"


REQUIRED_DOCS: list[tuple[str, str]] = [
    # Core architecture (001–010)
    ("001_PROJECT_ARCHITECTURE.md", "001 — PROJECT_ARCHITECTURE"),
    ("002_FRONTEND_UI_RULES.md", "002 — FRONTEND_UI_RULES"),
    ("003_DESIGN_SYSTEM.md", "003 — DESIGN_SYSTEM"),
    ("004_STATE_MANAGEMENT.md", "004 — STATE_MANAGEMENT"),
    ("005_RENDER_BACKEND_SETUP.md", "005 — RENDER_BACKEND_SETUP"),
    ("006_SUPABASE_SCHEMA.md", "006 — SUPABASE_SCHEMA"),
    ("007_API_RESPONSE_STANDARD.md", "007 — API_RESPONSE_STANDARD"),
    ("008_ERROR_HANDLING_SYSTEM.md", "008 — ERROR_HANDLING_SYSTEM"),
    ("009_LOADING_AND_SKELETONS.md", "009 — LOADING_AND_SKELETONS"),
    ("010_REALTIME_SYNC_ENGINE.md", "010 — REALTIME_SYNC_ENGINE"),

    # Purchase history + core purchase systems (020–029)
    ("020_PURCHASE_HISTORY_REBUILD.md", "020 — PURCHASE_HISTORY_REBUILD"),
    ("021_PURCHASE_SEARCH_ENGINE.md", "021 — PURCHASE_SEARCH_ENGINE"),
    ("022_PURCHASE_FILTER_SYSTEM.md", "022 — PURCHASE_FILTER_SYSTEM"),
    ("023_PURCHASE_TOTALS_ENGINE.md", "023 — PURCHASE_TOTALS_ENGINE"),
    ("024_PURCHASE_VALIDATION_RULES.md", "024 — PURCHASE_VALIDATION_RULES"),
    ("025_PURCHASE_STATUS_SYSTEM.md", "025 — PURCHASE_STATUS_SYSTEM"),
    ("026_PURCHASE_SORTING_SYSTEM.md", "026 — PURCHASE_SORTING_SYSTEM"),
    ("027_PURCHASE_CARD_UI.md", "027 — PURCHASE_CARD_UI"),
    ("028_PURCHASE_DETAIL_PAGE.md", "028 — PURCHASE_DETAIL_PAGE"),
    ("029_PURCHASE_CACHE_INVALIDATION.md", "029 — PURCHASE_CACHE_INVALIDATION"),

    # Global search rebuild (040–054)
    ("040_GLOBAL_SEARCH_REBUILD.md", "040 — GLOBAL_SEARCH_REBUILD"),
    ("041_SEARCH_INDEXING_ENGINE.md", "041 — SEARCH_INDEXING_ENGINE"),
    ("042_FUZZY_SEARCH_SYSTEM.md", "042 — FUZZY_SEARCH_SYSTEM"),
    ("043_TYPO_CORRECTION_ENGINE.md", "043 — TYPO_CORRECTION_ENGINE"),
    ("044_PHONETIC_MATCHING.md", "044 — PHONETIC_MATCHING"),
    ("045_MALAYALAM_MATCHING.md", "045 — MALAYALAM_MATCHING"),
    ("046_SEARCH_RESULT_RENDERING.md", "046 — SEARCH_RESULT_RENDERING"),
    ("047_CATEGORY_SEARCH.md", "047 — CATEGORY_SEARCH"),
    ("048_SUBCATEGORY_SEARCH.md", "048 — SUBCATEGORY_SEARCH"),
    ("049_SUPPLIER_SEARCH.md", "049 — SUPPLIER_SEARCH"),
    ("050_CONTACT_SEARCH.md", "050 — CONTACT_SEARCH"),
    ("051_BROKER_SEARCH.md", "051 — BROKER_SEARCH"),
    ("052_ITEM_SEARCH.md", "052 — ITEM_SEARCH"),
    ("053_PURCHASE_ID_SEARCH.md", "053 — PURCHASE_ID_SEARCH"),
    ("054_GLOBAL_SEARCH_PERFORMANCE.md", "054 — GLOBAL_SEARCH_PERFORMANCE"),

    # AI scan system (060–079)
    ("060_AI_SCAN_ARCHITECTURE.md", "060 — AI_SCAN_ARCHITECTURE"),
    ("061_OPENAI_VISION_PIPELINE.md", "061 — OPENAI_VISION_PIPELINE"),
    ("062_IMAGE_PREPROCESSING.md", "062 — IMAGE_PREPROCESSING"),
    ("063_HANDWRITING_ENHANCEMENT.md", "063 — HANDWRITING_ENHANCEMENT"),
    ("064_JSON_EXTRACTION_RULES.md", "064 — JSON_EXTRACTION_RULES"),
    ("065_AI_VALIDATION_FLOW.md", "065 — AI_VALIDATION_FLOW"),
    ("066_AI_CONFIDENCE_ENGINE.md", "066 — AI_CONFIDENCE_ENGINE"),
    ("067_AI_FALLBACK_SYSTEM.md", "067 — AI_FALLBACK_SYSTEM"),
    ("068_GEMINI_FALLBACK.md", "068 — GEMINI_FALLBACK"),
    ("069_GROQ_FALLBACK.md", "069 — GROQ_FALLBACK"),
    ("070_OCR_EMERGENCY_MODE.md", "070 — OCR_EMERGENCY_MODE"),
    ("071_SUPPLIER_MATCHING_AI.md", "071 — SUPPLIER_MATCHING_AI"),
    ("072_ITEM_MATCHING_AI.md", "072 — ITEM_MATCHING_AI"),
    ("073_UNIT_DETECTION_SYSTEM.md", "073 — UNIT_DETECTION_SYSTEM"),
    ("074_RATE_VALIDATION_SYSTEM.md", "074 — RATE_VALIDATION_SYSTEM"),
    ("075_AI_REVIEW_SCREEN.md", "075 — AI_REVIEW_SCREEN"),
    ("076_AI_LOADING_PROGRESS.md", "076 — AI_LOADING_PROGRESS"),
    ("077_AI_ERROR_HANDLING.md", "077 — AI_ERROR_HANDLING"),
    ("078_IMAGE_CROPPING_ENGINE.md", "078 — IMAGE_CROPPING_ENGINE"),
    ("079_SHADOW_REMOVAL_SYSTEM.md", "079 — SHADOW_REMOVAL_SYSTEM"),

    # Reports system (090–099)
    ("090_REPORTS_ENGINE.md", "090 — REPORTS_ENGINE"),
    ("091_REPORTS_AGGREGATION.md", "091 — REPORTS_AGGREGATION"),
    ("092_REPORTS_REALTIME_SYNC.md", "092 — REPORTS_REALTIME_SYNC"),
    ("093_REPORTS_CACHE_ENGINE.md", "093 — REPORTS_CACHE_ENGINE"),
    ("094_REPORTS_FILTERS.md", "094 — REPORTS_FILTERS"),
    ("095_REPORTS_DATE_RANGE_SYSTEM.md", "095 — REPORTS_DATE_RANGE_SYSTEM"),
    ("096_REPORTS_GRAPH_SYSTEM.md", "096 — REPORTS_GRAPH_SYSTEM"),
    ("097_REPORTS_EXPORT_SYSTEM.md", "097 — REPORTS_EXPORT_SYSTEM"),
    ("098_REPORTS_PDF_EXPORT.md", "098 — REPORTS_PDF_EXPORT"),
    ("099_REPORTS_EXCEL_EXPORT.md", "099 — REPORTS_EXCEL_EXPORT"),

    # Item analytics + detail (110–117)
    ("110_ITEM_ANALYTICS.md", "110 — ITEM_ANALYTICS"),
    ("111_ITEM_DETAIL_PAGE.md", "111 — ITEM_DETAIL_PAGE"),
    ("112_ITEM_PRICE_TRENDS.md", "112 — ITEM_PRICE_TRENDS"),
    ("113_ITEM_SUPPLIER_ANALYTICS.md", "113 — ITEM_SUPPLIER_ANALYTICS"),
    ("114_ITEM_PURCHASE_HISTORY.md", "114 — ITEM_PURCHASE_HISTORY"),
    ("115_ITEM_ROW_LAYOUT.md", "115 — ITEM_ROW_LAYOUT"),
    ("116_ITEM_TOTALS_VALIDATION.md", "116 — ITEM_TOTALS_VALIDATION"),
    ("117_ITEM_PERFORMANCE_ENGINE.md", "117 — ITEM_PERFORMANCE_ENGINE"),

    # Home dashboard (130–137)
    ("130_HOME_DASHBOARD.md", "130 — HOME_DASHBOARD"),
    ("131_HOME_TOTALS_ENGINE.md", "131 — HOME_TOTALS_ENGINE"),
    ("132_HOME_REALTIME_COUNTS.md", "132 — HOME_REALTIME_COUNTS"),
    ("133_HOME_CHARTS_SYSTEM.md", "133 — HOME_CHARTS_SYSTEM"),
    ("134_HOME_QUICK_FILTERS.md", "134 — HOME_QUICK_FILTERS"),
    ("135_HOME_PERIOD_FILTERS.md", "135 — HOME_PERIOD_FILTERS"),
    ("136_HOME_PROFIT_ENGINE.md", "136 — HOME_PROFIT_ENGINE"),
    ("137_HOME_REFRESH_SYSTEM.md", "137 — HOME_REFRESH_SYSTEM"),

    # WhatsApp automation (150–155)
    ("150_WHATSAPP_AUTOMATION.md", "150 — WHATSAPP_AUTOMATION"),
    ("151_WHATSAPP_REPORT_SCHEDULER.md", "151 — WHATSAPP_REPORT_SCHEDULER"),
    ("152_WHATSAPP_RETRY_SYSTEM.md", "152 — WHATSAPP_RETRY_SYSTEM"),
    ("153_WHATSAPP_QUEUE_SYSTEM.md", "153 — WHATSAPP_QUEUE_SYSTEM"),
    ("154_WHATSAPP_ERROR_RECOVERY.md", "154 — WHATSAPP_ERROR_RECOVERY"),
    ("155_WHATSAPP_DELIVERY_STATUS.md", "155 — WHATSAPP_DELIVERY_STATUS"),

    # Settings + background jobs (170–175)
    ("170_SETTINGS_SYSTEM.md", "170 — SETTINGS_SYSTEM"),
    ("171_NOTIFICATION_ENGINE.md", "171 — NOTIFICATION_ENGINE"),
    ("172_BACKGROUND_JOBS.md", "172 — BACKGROUND_JOBS"),
    ("173_QUEUE_PROCESSING.md", "173 — QUEUE_PROCESSING"),
    ("174_CRASH_RECOVERY.md", "174 — CRASH_RECOVERY"),
    ("175_PROVIDER_LIFECYCLE_RULES.md", "175 — PROVIDER_LIFECYCLE_RULES"),

    # DB/perf (190–197)
    ("190_DATABASE_OPTIMIZATION.md", "190 — DATABASE_OPTIMIZATION"),
    ("191_QUERY_OPTIMIZATION.md", "191 — QUERY_OPTIMIZATION"),
    ("192_BACKGROUND_AGGREGATION.md", "192 — BACKGROUND_AGGREGATION"),
    ("193_CACHE_INVALIDATION.md", "193 — CACHE_INVALIDATION"),
    ("194_REALTIME_SUBSCRIPTIONS.md", "194 — REALTIME_SUBSCRIPTIONS"),
    ("195_INDEXING_STRATEGY.md", "195 — INDEXING_STRATEGY"),
    ("196_LARGE_DATASET_TESTING.md", "196 — LARGE_DATASET_TESTING"),
    ("197_PERFORMANCE_BENCHMARKS.md", "197 — PERFORMANCE_BENCHMARKS"),

    # Security (210–215)
    ("210_SECURITY_RULES.md", "210 — SECURITY_RULES"),
    ("211_API_RATE_LIMITS.md", "211 — API_RATE_LIMITS"),
    ("212_INPUT_VALIDATION.md", "212 — INPUT_VALIDATION"),
    ("213_JSON_SCHEMA_VALIDATION.md", "213 — JSON_SCHEMA_VALIDATION"),
    ("214_UPLOAD_SECURITY.md", "214 — UPLOAD_SECURITY"),
    ("215_IMAGE_VALIDATION.md", "215 — IMAGE_VALIDATION"),

    # UI/UX fixes (230–237)
    ("230_UI_UX_FIXES.md", "230 — UI_UX_FIXES"),
    ("231_FORM_ALIGNMENT_RULES.md", "231 — FORM_ALIGNMENT_RULES"),
    ("232_BUTTON_LAYOUT_RULES.md", "232 — BUTTON_LAYOUT_RULES"),
    ("233_KEYBOARD_OVERLAY_FIXES.md", "233 — KEYBOARD_OVERLAY_FIXES"),
    ("234_BOTTOM_SHEET_RULES.md", "234 — BOTTOM_SHEET_RULES"),
    ("235_RESPONSIVE_LAYOUT_SYSTEM.md", "235 — RESPONSIVE_LAYOUT_SYSTEM"),
    ("236_SPACING_AND_GRID_SYSTEM.md", "236 — SPACING_AND_GRID_SYSTEM"),
    ("237_COLOR_AND_STATUS_SYSTEM.md", "237 — COLOR_AND_STATUS_SYSTEM"),

    # Tracking + release (250–255)
    ("250_BUG_TRACKER.md", "250 — BUG_TRACKER"),
    ("251_KNOWN_ISSUES.md", "251 — KNOWN_ISSUES"),
    ("252_PENDING_OPTIMIZATIONS.md", "252 — PENDING_OPTIMIZATIONS"),
    ("253_RELEASE_CHECKLIST.md", "253 — RELEASE_CHECKLIST"),
    ("254_PRODUCTION_DEPLOYMENT.md", "254 — PRODUCTION_DEPLOYMENT"),
    ("255_MONITORING_AND_ALERTS.md", "255 — MONITORING_AND_ALERTS"),

    # Terms page rebuild (110–118)
    ("110_TERMS_PAGE_REBUILD.md", "110 — TERMS_PAGE_REBUILD"),
    ("111_BROKER_COMMISSION_SYSTEM.md", "111 — BROKER_COMMISSION_SYSTEM"),
    ("112_KEYBOARD_SAFEAREA_FIXES.md", "112 — KEYBOARD_SAFEAREA_FIXES"),
    ("113_SCROLL_AND_LAYOUT_RULES.md", "113 — SCROLL_AND_LAYOUT_RULES"),
    ("114_INPUT_VALIDATION_RULES.md", "114 — INPUT_VALIDATION_RULES"),
    ("115_MOBILE_FORM_UX.md", "115 — MOBILE_FORM_UX"),
    ("116_WHOLESALE_BROKER_LOGIC.md", "116 — WHOLESALE_BROKER_LOGIC"),
    ("117_STICKY_CTA_SYSTEM.md", "117 — STICKY_CTA_SYSTEM"),
    ("118_SAFE_AREA_AND_KEYBOARD.md", "118 — SAFE_AREA_AND_KEYBOARD"),
    # WhatsApp system rebuild (120–130)
    ("120_WHATSAPP_REPORT_SYSTEM.md", "120 — WHATSAPP_REPORT_SYSTEM"),
    ("121_BACKGROUND_JOB_QUEUE.md", "121 — BACKGROUND_JOB_QUEUE"),
    ("122_PROVIDER_LIFECYCLE_FIXES.md", "122 — PROVIDER_LIFECYCLE_FIXES"),
    ("123_ASYNC_STATE_RULES.md", "123 — ASYNC_STATE_RULES"),
    ("124_RETRY_AND_TIMEOUT_SYSTEM.md", "124 — RETRY_AND_TIMEOUT_SYSTEM"),
    ("125_REPORT_DELIVERY_FLOW.md", "125 — REPORT_DELIVERY_FLOW"),
    ("126_WHATSAPP_UI_REBUILD.md", "126 — WHATSAPP_UI_REBUILD"),
    ("127_PRODUCTION_ERROR_HANDLING.md", "127 — PRODUCTION_ERROR_HANDLING"),
    ("128_OFFLINE_REPORT_QUEUE.md", "128 — OFFLINE_REPORT_QUEUE"),
    ("129_REPORT_PDF_PIPELINE.md", "129 — REPORT_PDF_PIPELINE"),
    ("130_NOTIFICATION_FEEDBACK_RULES.md", "130 — NOTIFICATION_FEEDBACK_RULES"),
    # System rebuild docs (201–220)
    ("201_OPENAI_VISION_PIPELINE.md", "201 — OPENAI_VISION_PIPELINE"),
    ("202_GLOBAL_SEARCH_REBUILD.md", "202 — GLOBAL_SEARCH_REBUILD"),
    ("203_REPORTS_ENGINE_REBUILD.md", "203 — REPORTS_ENGINE_REBUILD"),
    ("204_REALTIME_TOTALS_SYSTEM.md", "204 — REALTIME_TOTALS_SYSTEM"),
    ("205_CACHE_INVALIDATION_RULES.md", "205 — CACHE_INVALIDATION_RULES"),
    ("206_ITEM_DETAIL_ARCHITECTURE.md", "206 — ITEM_DETAIL_ARCHITECTURE"),
    ("207_AI_VALIDATION_PIPELINE.md", "207 — AI_VALIDATION_PIPELINE"),
    ("208_SUPPLIER_MATCHING_ENGINE.md", "208 — SUPPLIER_MATCHING_ENGINE"),
    ("209_REPORT_FILTER_SYSTEM.md", "209 — REPORT_FILTER_SYSTEM"),
    ("210_ADVANCED_SEARCH_INDEXING.md", "210 — ADVANCED_SEARCH_INDEXING"),
    ("211_BACKGROUND_AGGREGATION.md", "211 — BACKGROUND_AGGREGATION"),
    ("212_DASHBOARD_SYNC_ENGINE.md", "212 — DASHBOARD_SYNC_ENGINE"),
    ("213_PURCHASE_TOTALS_VALIDATION.md", "213 — PURCHASE_TOTALS_VALIDATION"),
    ("214_HANDWRITING_ENHANCEMENT_PIPELINE.md", "214 — HANDWRITING_ENHANCEMENT_PIPELINE"),
    ("215_JSON_EXTRACTION_SYSTEM.md", "215 — JSON_EXTRACTION_SYSTEM"),
    ("216_ERROR_HANDLING_RULES.md", "216 — ERROR_HANDLING_RULES"),
    ("217_LOADING_AND_SKELETONS.md", "217 — LOADING_AND_SKELETONS"),
    ("218_REPORT_EXPORT_SYSTEM.md", "218 — REPORT_EXPORT_SYSTEM"),
    ("219_PRICE_TREND_ANALYTICS.md", "219 — PRICE_TREND_ANALYTICS"),
    ("220_AI_CONFIDENCE_SCORING.md", "220 — AI_CONFIDENCE_SCORING"),
]


def load_template() -> str:
    t = TEMPLATE_PATH.read_text(encoding="utf-8")
    if "<TITLE>" not in t:
        raise RuntimeError("Template missing <TITLE> placeholder")
    return t


def ensure_docs_dir() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)


def write_doc(path: Path, title: str, template: str) -> bool:
    if path.exists():
        return False
    content = template.replace("<TITLE>", title)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    ensure_docs_dir()
    if not TEMPLATE_PATH.exists():
        raise RuntimeError(f"Missing template: {TEMPLATE_PATH}")
    template = load_template()

    created = 0
    skipped = 0
    for filename, title in REQUIRED_DOCS:
        p = DOCS_DIR / filename
        if write_doc(p, title, template):
            created += 1
        else:
            skipped += 1

    print(f"strict-docs: created={created} skipped={skipped} in {DOCS_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

